# Generated by Django 3.1.3 on 2023-08-15 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230815_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_content',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='answer',
            new_name='is_correct',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questions',
        ),
    ]
